/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Pifko
 */
public class ytdlFRAME extends javax.swing.JFrame {

    /**
     * Creates new form ytdlFRAME
     */
    public ytdlFRAME() {
        initComponents();
    }

    public JButton getDlButton() {
        return dlButton;
    }

    public JTextField getYtlinkTEXTFIELD() {
        return ytlinkTEXTFIELD;
    }

    public JTextArea getConsole() {
        return Console;
    }

    public JButton getInfoBTN() {
        return infoBTN;
    }

    public JCheckBox getFormatCodeBox() {
        return FormatCodeBox;
    }

    public JComboBox getFormatCodeList() {
        return FormatCodeList;
    }

    public JProgressBar getDlbar() {
        return dlbar;
    }

    public JButton getStopdl() {
        return Stopdl;
    }

    public JTextField getDlspeedlimit() {
        return Dlspeedlimit;
    }

    public JCheckBox getLimitspeedcheck() {
        return Limitspeedcheck;
    }
    
    
    
    public void setuiconfig(){
    
        this.dlbar.setValue(0);
        this.dlbar.setStringPainted(true);
        
        DefaultCaret caret = (DefaultCaret)Console.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        this.setLocationRelativeTo(null);
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dlButton = new javax.swing.JButton();
        ytlinkTEXTFIELD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Console = new javax.swing.JTextArea();
        infoBTN = new javax.swing.JButton();
        FormatCodeBox = new javax.swing.JCheckBox();
        FormatCodeList = new javax.swing.JComboBox();
        dlbar = new javax.swing.JProgressBar();
        Stopdl = new javax.swing.JButton();
        Limitspeedcheck = new javax.swing.JCheckBox();
        Dlspeedlimit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YTDL");

        dlButton.setText("Download");

        jLabel1.setText("YT Link:");

        Console.setEditable(false);
        Console.setColumns(20);
        Console.setRows(5);
        Console.setFocusable(false);
        jScrollPane2.setViewportView(Console);

        infoBTN.setText("GetInfo");

        FormatCodeBox.setText("Format code:");

        dlbar.setToolTipText("");

        Stopdl.setText("Stop Download");

        Limitspeedcheck.setText("Limit speed:");

        Dlspeedlimit.setText("100000");

        jLabel2.setText("KB/s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ytlinkTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(Limitspeedcheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dlspeedlimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(dlButton)
                                .addGap(63, 63, 63)
                                .addComponent(infoBTN)
                                .addGap(117, 117, 117)
                                .addComponent(dlbar, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addComponent(FormatCodeBox)
                        .addGap(18, 18, 18)
                        .addComponent(FormatCodeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Stopdl)
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormatCodeBox)
                    .addComponent(FormatCodeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stopdl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ytlinkTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Limitspeedcheck)
                    .addComponent(Dlspeedlimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlButton)
                    .addComponent(infoBTN)
                    .addComponent(dlbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Console;
    private javax.swing.JTextField Dlspeedlimit;
    private javax.swing.JCheckBox FormatCodeBox;
    private javax.swing.JComboBox FormatCodeList;
    private javax.swing.JCheckBox Limitspeedcheck;
    private javax.swing.JButton Stopdl;
    private javax.swing.JButton dlButton;
    private javax.swing.JProgressBar dlbar;
    private javax.swing.JButton infoBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ytlinkTEXTFIELD;
    // End of variables declaration//GEN-END:variables


}
